-- AlterTable
ALTER TABLE "users" ADD COLUMN     "ama" TEXT,
ADD COLUMN     "city_id" INTEGER,
ADD COLUMN     "custom_city" TEXT,
ADD COLUMN     "deleted_at" TIMESTAMP(3),
ADD COLUMN     "image_path" TEXT,
ADD COLUMN     "phone_verification_status" BOOLEAN,
ADD COLUMN     "phone_verified_with" TEXT,
ADD COLUMN     "remember_token" TEXT,
ADD COLUMN     "tz" TEXT,
ADD COLUMN     "unsubscribe_link" TEXT,
ADD COLUMN     "verified_at" TIMESTAMP(3),
ADD COLUMN     "verified_certificate_name" TEXT,
ADD COLUMN     "verified_identity_document" TEXT,
ALTER COLUMN "password" DROP NOT NULL;
